updated 7

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -63,7 +63,12 @@ jobs:
           fetch-depth: 0
 
       - name: Clean build directory
-        run: rm -rf build/
+        run: |
+          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
+            rd /s /q build 2> nul || echo "Build dir not found"
+          else
+            rm -rf build
+          fi
 
       - name: Build
         shell: bash
